version: '3.7'

services:
  laravel:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: laravel_app
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laraveluser
      DB_PASSWORD: secret
    restart: unless-stopped
    working_dir: /var/www/laravel
    volumes:
      - './project/laravel:/var/www/laravel'
    networks:
      - app-network
    depends_on:
      - db  
    user: root

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
      - './project/laravel:/var/www/laravel'
    depends_on:
      - laravel
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootpassword
    command: --bind-address=0.0.0.0  --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network       

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: